language: java

jdk:
  - oraclejdk8

before_install:
  - npm install webpack elm@0.18
  - npm install
  - elm-package install
  - chmod +x ./gradlew

script:
  - ./gradlew test integrationTest --stacktrace